# Goal
std_msgs/Header header
int64 timestamp           # 纳秒时间戳
int64 index               # 消息序列号

geometry_msgs/Point ball_position
geometry_msgs/Vector3 kick_direction
float32 kick_speed
uint8 FOOT_LEFT = 1
uint8 FOOT_RIGHT = 2
uint8 kick_foot

---
# Result
bool success
string message

---
# Feedback
string state
float32 distance_to_ball
